user_interface/ui_app/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path
from . import views

app_name = 'ui_app'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    path('api/files/<int:receipt_id>', views.api, name='api'),
    path('receipt/<int:receipt_id>', views.receipt, name='receipt'),
]

user_interface/user_interface/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ui_app.urls')),
]

user_interface/ui_app/models.py
from django.db import models


class Products(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=45)
    energy = models.FloatField(blank=True, null=True)
    fat = models.FloatField(blank=True, null=True)
    carbohydrate = models.FloatField(blank=True, null=True)
    protein = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'products'

class Receipts(models.Model):
    receipt_id = models.AutoField(primary_key=True)
    receipt_name = models.CharField(max_length=45)
    date = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'receipts'


class ReceiptsContent(models.Model):
    id = models.AutoField(primary_key=True)
    receipt = models.ForeignKey(Receipts, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.FloatField(blank=True, null=True)
    unit_of_measurement = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'receipts_content'


class ReceiptProcessingLogs(models.Model):
    receipt = models.ForeignKey('Receipts', models.DO_NOTHING, blank=True, null=True)
    message = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'receipt_processing_logs'

user_interface/ui_app/forms.py
from django import forms
from .models import Products

#class UploadFileForm(forms.ModelForm):
#    class Meta:
#        model = Products
#        fields = ['product_name', 'fat', 'carbohydrate', 'protein']
#        labels = {'product_name': 'product', }
#        widject = {
#            'product_name': forms.TextInput(attrs={
#                'max_length': '100'
#            })
#        }

class UploadFileForm(forms.Form):
     file = forms.FileField() # for creating file input  

user_interface/ui_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings

import pika, json, re, math

from .forms import UploadFileForm
from .models import Products, Receipts, ReceiptProcessingLogs, ReceiptsContent

def index(request):
    """The home page for nutrition project"""
    receipts = Receipts.objects.order_by('receipt_id')
    arr = upload_file_form(request)

    context = {'receipts': receipts, 'form': arr['form'], 'receipt_id': arr['receipt_id']}
    return render(request, 'ui_app/index.html', context)


def receipt(request, receipt_id):
    """Nutrition information for specific receipt"""
    products = ReceiptsContent.objects.all().filter(receipt_id = receipt_id).select_related("product")
    pcf = count_totals(products)
    context = {'products': products, 'pcf': pcf}
    return render(request, 'ui_app/receipt.html', context)

def count_totals(products):
    """What PFC a day we have as a result"""
    energy = 0
    fat = 0
    carbohydrate = 0
    protein = 0
    for product in products:
        energy += product.product.energy
        fat += product.product.fat
        carbohydrate += product.product.carbohydrate
        protein += product.product.protein
    
    # Calculations are based on the following suggestions:
    # There are 3 people in the family and products are purchased once a week
    # we have data in kgs and for 100g == 10

    energy = math.ceil(energy * product.quantity * 10 /3 /7)
    fat = math.ceil(fat * product.quantity * 10 /3 /7)
    carbohydrate = math.ceil(carbohydrate * product.quantity * 10 /3 /7)
    protein = math.ceil(protein * product.quantity * 10 /3 /7)

    p = math.ceil((protein * 4 * 100) / energy) 
    f = math.ceil((fat * 9 * 100) / energy)
    c = math.ceil((carbohydrate * 3.75 * 100) / energy)
    ratio = f"{c}:{f}:{p}"

    return {'quantity': product.quantity, 'energy': energy, 'fat': fat, 'carbohydrate': carbohydrate, 'protein': protein, 'ratio': ratio}


def upload_file_form(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        print("request_method is post")
        # create a form instance and populate it with data from the request:
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():  
            handle_uploaded_file(request.FILES['file'])
            receipt_id = save_file_to_db(request.FILES['file'])
            update_logs_table(receipt_id, 'The receipt name has been stored to DB')
            send_message_to_queue(receipt_id, request.FILES['file'])
            return {'form': '', 'receipt_id': receipt_id, 'file': request.FILES['file']} 
    # if a GET (or any other method) we'll create a blank form
    else:
        form = UploadFileForm()
        receipt_id = ''

    return {'form': form, 'receipt_id': receipt_id}

def handle_uploaded_file(file):
    with open('ui_app/media/'+file.name, 'wb+') as destination:  
        for chunk in file.chunks():  
            destination.write(chunk)


def save_file_to_db(file):
    print('save receipt to db')
    receipt = Receipts()
    receipt.receipt_name = file
    receipt.date = ''
    receipt.save()
    return receipt.pk

def update_logs_table(receipt_id, message):
    print('save log')
    receipt = Receipts()
    receipt.receipt_id = receipt_id
    print('receipt_id', receipt_id)
    log = ReceiptProcessingLogs()
    log.receipt = receipt
    log.message = message
    log.save()
    return log.pk

def send_message_to_queue(receipt_id, file):

    file_name = str(file)
    data = {'receipt_id': receipt_id, 'file_name': file_name}
    
    connection = pika.BlockingConnection(
        pika.ConnectionParameters(settings.MQ_HOSTNAME))
    channel = connection.channel()
    channel.queue_declare(queue='received_new_pdf')
    channel.basic_publish(exchange='', routing_key='received_new_pdf', body=json.dumps(data))
    print(" [x] Sent 'Hello World!'")
    connection.close()


@csrf_exempt
def api(request, receipt_id):
    messages = ReceiptProcessingLogs.objects.all().filter(receipt_id=receipt_id)
    saved = 0
    retreived = 0
    all_products = 0
    logs = []
    for message in messages:
        logs.append(message.message)
        if(re.search('saved', message.message)):
            saved += 1
        elif(re.search('nutrition', message.message)):
            retreived += 1
        elif(re.search('All products', message.message)):
            all_products += 1

    if saved == retreived and all_products == 1:
        status = 'completed'
    else:
        status = 'in progress' 

    responce = {
        'receipt_id': receipt_id,
        'status': status,
        'saved': saved,
        'retreived': retreived,
        'logs': logs
    }
    return JsonResponse(responce, safe=False)

user_interface/ui_app/templates/ui_app/base.html
{% load bootstrap4 %}
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="icon" href="data:;base64,iVBORw0KGgo=">
		<title>Nutrition</title>

		{% bootstrap_css %}
		{% bootstrap_javascript jquery='full' %}
		{% load static %}

		
		<script type="text/javascript" src="{{ STATIC_URL }} /static/jquery-3.6.3.js">
		</script> 

	</head>

	<body>
		<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
			
		</nav>

		<main role="main" class="container">
			<div class="pb-2 mb-2 border-bottom">
				{% block page_header %}{% endblock page_header %}
			</div>
			<div>
				{% block content %}{% endblock content %}
			</div>
		</main>
	</body>
</html>

user_interface/ui_app/templates/ui_app/index.html
{% extends 'ui_app/base.html' %}

{% block page_header %}
    <h1>Nutrition project.</h1>
    <h3>Nutrition project will help you track how healthy your diet is according to your grocery purchases.</h3>
{% endblock page_header %}

{% block content %}
<p>

    <p> Receipts that have been downloaded already: </p>
<ul class="list-group list-group-flush">
    {% for receipt in receipts %}
      <li class="list-group-item">
        <a href="{% url 'ui_app:receipt' receipt.receipt_id %}"> {{ receipt.date }} </a>
      </li>
    {% empty %}
        <p>No receipts have been downloaded yet</p>
    {% endfor %}
</ul>

{% if form != '' %}
<div id="file_upload_form">
  <p>You can download a file here: </p>
  <form action="{% url 'ui_app:index' %}" method="post"  enctype="multipart/form-data" >
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" id="form_submit">
  </form>
</div>
{% endif %}


<div class="spinner-border text-info" role="status" id="loader">
    <span class="sr-only">Loading...</span>
</div>

<div id="logs">
    <p>Receipt processing is in progress:</p>
    <ul class="list-group list-group-flush"></ul>
</div>

<style type="text/css">
    #loader{
      display: none;
    }
    #logs{
      display: none;
    }
</style>

<script>

  var currently_processing_file = "{{ receipt_id }}";
  var spinner = $('#loader');
  var my_form = $('#file_upload_form');
  var logs = $('#logs');
  var status = '';

  function checkStatus(){

    if (currently_processing_file != ''){
        console.log('receipt id: ', currently_processing_file);
        spinner.show()


        $.ajax({
          url: 'api/files/' + currently_processing_file,
          method: 'POST',
          dataType: 'JSON',
          success: function(responce){
            status = responce.status;
            saved = responce.saved;
            retreived = responce.retreived;
            if (status == 'in progress'){
              setTimeout(checkStatus, 2000);
              my_form.hide();
              logs.show();
              $('#logs ul').empty();
              for (i = 0; i < responce.logs.length; i++){
                $('#logs ul').append( "<li class='list-group-item'>"+responce.logs[i]+"</li>" );
              }
            }else{
              /* reload page without sending POST data again */
              window.location.href = window.location.href;
            }
          }
        })
     }

  }



  $(document).ready(function(){
    setTimeout(checkStatus, 1000);
  })



  

</script>

</p>
{% endblock content %}

user_interface/ui_app/templates/ui_app/receipt.html
{% extends 'ui_app/base.html' %}

{% block page_header %}
    <h1>Nutrition project.</h1>
    <h3>Nutrition project will help you track how healthy your diet is according to your grocery purchases.</h3>
{% endblock page_header %}

{% block content %}
<p>
    <div>
        <p>Note: The acceptable macronutrient distribution ranges are:
        45–65% of your daily calories from carbs, 
        20–35% from fats and 
        10–35% from protein.</p>
        <p>Your ratio this week is <span>{{pcf.ratio}}</span></p>
        <p>Following calculations are based on the suggestion 
            that there are 3 people in the family and products are purchased once a week:</p>
    </div>

<table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Quantity</th>
        <th scope="col">Enegry</th>
        <th scope="col">Fat</th>
        <th scope="col">Carbs</th>
        <th scope="col">Proteins</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ product.product.product_name }}</td>
        <td>{{ product.unit_of_measurement }}</td>
        <td>{{ product.product.energy }}</td>
        <td>{{ product.product.fat }}</td>
        <td>{{ product.product.carbohydrate }}</td>
        <td>{{ product.product.protein }}</td>
      </tr>
    {% endfor %}
      <tr>
        <th colspan="2" scope="row">In a day: </th>
        <td></td>
        <td>{{ pcf.energy }}</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </table>

{% endblock content %}